### ISSUE TITLE
fsck.te Error ["unknown type" because in device/qcom/sepolicy was pointing to vendor/cm instead of vendor/aokp]

### ISSUE THREAD

**Issue by MoistPicklez** [MarshMallowKang/device_oneplus_bacon#1]
device/oneplus/bacon/sepolicy/fsck.te:2:ERROR 'unknown type persist_block_device' at token ';' on line 26521:
allow fsck persist_block_device:blk_file { { getattr open read ioctl lock } { open append write } };
# line 1 "device/oneplus/bacon/sepolicy/fsck.te"

checkpolicy:  error(s) encountered while parsing configuration
make: **\* [/home/adzcache/android/aokp/out/target/product/bacon/obj/ETC/sepolicy_intermediates/sepolicy] Error 1

**Comment by STELIX** [comment]
sepolicy files are currently still in updating stage...

**Comment by STELIX** [comment]
["unknown type" because in device/qcom/sepolicy was pointing to vendor/cm instead of vendor/aokp]

**Comment by MoistPicklez** [comment]
![13hourdeath](https://cloud.githubusercontent.com/assets/15859993/11475416/2fcd7b72-9732-11e5-8703-5b1f9125331d.png)

**Comment by MoistPicklez** [comment]
13 hours and failed LOL

**Comment by STELIX** [comment]
LOL u need a new pc mate. Dunno how it can't find build.prop in your out directory... here was fine.

**Comment by MoistPicklez** [comment]
I know, my PC is horrible. I will try again another day. 
(｡ŏ_ŏ)

**Comment by STELIX** [comment]
Np. I appreciate a lot more your tryes, instead of certain other buddies... 88% check on hangout...
